import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";

const STORAGE_KEY_DISCLAIMER = "inkwell-disclaimer-accepted";

export function DisclaimerDialog() {
  const [isOpen, setIsOpen] = useState(false);
  const [isAccepted, setIsAccepted] = useState(false);

  useEffect(() => {
    const hasAccepted = localStorage.getItem(STORAGE_KEY_DISCLAIMER);
    if (!hasAccepted) {
      setIsOpen(true);
    }
  }, []);

  const handleAgree = () => {
    localStorage.setItem(STORAGE_KEY_DISCLAIMER, "true");
    setIsOpen(false);
  };

  return (
    <Dialog open={isOpen} onOpenChange={() => {}}>
      <DialogContent className="sm:max-w-[425px]" onPointerDownOutside={(e) => e.preventDefault()} onEscapeKeyDown={(e) => e.preventDefault()}>
        <DialogHeader>
          <DialogTitle>Welcome to Inkwell</DialogTitle>
          <DialogDescription>
            Please read the following disclaimer before proceeding.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4 text-sm text-muted-foreground">
          <ul className="list-disc pl-4 space-y-2">
            <li>
              <strong>Privacy:</strong> We do not collect ANY personal information. All data is sent directly to the API server you configure (e.g., OpenAI).
            </li>
            <li>
              <strong>Quality:</strong> We do not provide any guarantee regarding the quality, accuracy, or safety of the text generated by the AI.
            </li>
            <li>
              <strong>Experimental:</strong> This application is for experimental purposes only. Do not use it for critical production workloads.
            </li>
          </ul>
        </div>
        <div className="flex items-center space-x-2 py-4">
          <Checkbox 
            id="terms" 
            checked={isAccepted} 
            onCheckedChange={(checked) => setIsAccepted(checked as boolean)} 
          />
          <Label htmlFor="terms" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            I am over 18 and I agree with the above.
          </Label>
        </div>
        <DialogFooter>
          <Button onClick={handleAgree} disabled={!isAccepted} className="w-full">
            Agree & Continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}